projects:
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma.yml
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000 # This endpoint is the GraphQL Playground Web App


# got this file from https://www.prisma.io/tutorials/build-a-graphql-server-from-scratch-ct01